### PR TITLE
Document MSRV

### PR DESCRIPTION
**Pull request by eldruin**
See: https://github.com/rust-embedded/wg/issues/445

### CODE REVIEW

**Review by paoloteti — DISMISSED** [review]

**Comment by adamgreig** [comment]
bors r=paoloteti

**Comment by paoloteti** [comment]
@eldruin Even if unrelated to this PR, could you submit a PR to fix CI issue?

**Comment by eldruin** [comment]
@paoloteti Sure. I just added the changes here. I am not sure why Travis has not run yet, though.

**Comment by paoloteti** [comment]
> 
> @paoloteti Sure. I just added the changes here. I am not sure why Travis has not run yet, though.

@eldruin Usually is due to an invalid yml file. You can check it at https://config.travis-ci.com/explore

**Comment by eldruin** [comment]
@paoloteti I reverted the change to the yml file as a test but there is still no build. Do you have any other idea?
The checker reported no problems anyway.

**Comment by paoloteti** [comment]
bors try

**Comment by eldruin** [comment]
Ok I added the warnings denial on CI again.

**Review by paoloteti — APPROVED** [review]

**Pull request merged**
